### ISSUE TITLE
Validation error in wgpu on Win10

### ISSUE THREAD

**Issue by simonsan** [sharkdp/binocle#24]
```
[2021-10-03T21:36:28Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `pixels_command_encoder`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

', C:\Users\Jameson\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.10.2\src\backend\direct.rs:2160:5
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Anything I can help with to diagnose the problem?

**Comment by rhysd** [comment]
This also occurs on macOS 10.15.

```
> binocle target/debug/fixred
[2021-10-04T07:39:03Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `pixels_command_encoder`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

', /Users/rhysd/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.2/src/backend/direct.rs:2160:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
-[_MTLCommandEncoder dealloc]:70: failed assertion `Command encoder released without endEncoding'
[1]    87724 abort      binocle target/debug/fixred
```

**Comment by quackduck** [comment]
Also occurs on macOS 11.6, 2017 Intel Macbook Air:

```shell
[2021-10-04T17:58:15Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `pixels_command_encoder`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.2/src/backend/direct.rs:2160:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
-[_MTLCommandEncoder dealloc]:131: failed assertion `Command encoder released without endEncoding'
```

**Comment by sharkdp** [comment]
Thank you for reporting this. I don't have a (native) Windows or MacOS system to test. I kind of just hoped that the binaries would work.

Any help would be very much appreciated.

The error seems to originate from wgpu (https://github.com/gfx-rs/wgpu/blob/76bcd9c494a4359853bc2caec8eebbaa990a34e3/wgpu-core/src/command/draw.rs#L92-L93, https://github.com/gfx-rs/wgpu/blob/76bcd9c494a4359853bc2caec8eebbaa990a34e3/wgpu-core/src/command/render.rs#L1221-L1227). There are a few (possibly) related issues on GitHub (e.g. https://github.com/iced-rs/iced/issues/816).

It might have to do with the absolute WIDTH/HEIGHT parameters (and the actual screen size?) that are set for binocle here:
https://github.com/sharkdp/binocle/blob/db70c421c16fc528097559bea68a616b12a7906c/src/settings.rs#L3-L4

Maybe someone could test setting them to other (lower?) values like 800x600?

**Comment by simonsan** [comment]
> Maybe someone could test setting them to other (lower?) values like 800x600?

I tried it, but still get the same error.

**Comment by rhysd** [comment]
`set_scissor_rect` is only called here in `egui_wgpu_backend` crate.

https://github.com/hasenbanck/egui_wgpu_backend/blob/74f63a071ff6578688f18d8091bf549d417b2c8f/src/lib.rs#L335

**Comment by rhysd** [comment]
I'm not sure, but the assertion says it should be

```rust
rect.x + rect.w > info.extent.width
```

so it means

```rust
rect.w > info.extent.width - rect.x
```

However, from `egui_wgpu_backend`,

```rust
let width = width.min(physical_width - x);
```

When `physical_width - x` is smaller than `width` in rhs, `width` in lhs is `physical_width - x` so

```rust
width == physical_width - x
```

This looks violating the assertion, doesn't it?

**Comment by simonsan** [comment]
I checked it on my Debian 11 system and it throws the same error.

**Comment by tan-wei** [comment]
Met the same issue on MacOS.

**Comment by pokemium** [comment]
Same problem occurred on M1 MacOS.

## Environment

```sh
Model Name: MacBook Air
Model Identifier: MacBookAir10,1
Chip: Apple M1
Memory: 16 GB
OS: macOS Big Sur 11.4

# use cargo for install
cargo 1.55.0 (32da73ab1 2021-08-23)
```

## Log

```sh
❯ env RUST_BACKTRACE=full binocle PM_PRISM.gbc
[2021-10-07T19:36:02Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `pixels_command_encoder`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

', /Users/akatsuki/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.2/src/backend/direct.rs:2160:5
stack backtrace:
   0:        0x10487c904 - std::backtrace_rs::backtrace::libunwind::trace::h5bc01f52da331a76
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10487c904 - std::backtrace_rs::backtrace::trace_unsynchronized::hed9f5f7d35868621
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10487c904 - std::sys_common::backtrace::_print_fmt::hbabfbab394a5b2a4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10487c904 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he94cf96d727dca88
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x104897d5c - core::fmt::write::hba755d202326a972
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:        0x10487a45c - std::io::Write::write_fmt::h2e794551090dcd0d
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:        0x10487e390 - std::sys_common::backtrace::_print::hb13f9bf532a85f20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10487e390 - std::sys_common::backtrace::print::h8bcbb8e054752f0b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10487e390 - std::panicking::default_hook::{{closure}}::ha49ee092c99defdc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:        0x10487dec4 - std::panicking::default_hook::h878922f48a642f60
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:        0x10487e9d8 - std::panicking::rust_panic_with_hook::h1daadfa06b290a08
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:        0x10487e520 - std::panicking::begin_panic_handler::{{closure}}::h34f1299f5ae837e5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:        0x10487cd94 - std::sys_common::backtrace::__rust_end_short_backtrace::hcec1a6222a82e10c
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10487e484 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:        0x1048b7bd4 - std::panicking::begin_panic_fmt::he2b82579df33f7af
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  15:        0x1047b8fac - wgpu::backend::direct::default_error_handler::hc7e3e0a37009e08a
  16:        0x1047b2a84 - core::ops::function::Fn::call::h1d2c8c7dcf7edc4e
  17:        0x1047b89b0 - <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass::hf68437ce966ff6b5
  18:        0x1046cf97c - egui_wgpu_backend::RenderPass::execute::hb4df5759194e7835
  19:        0x1046209b4 - binocle::gui::Gui::render::h892d5ec1ba3a8a9a
  20:        0x10461c0a0 - pixels::Pixels::render_with::h093666ade3a4adce
  21:        0x104619680 - binocle::event_loop::run::{{closure}}::h554a59b3d1bbeaa0
  22:        0x10461a4e4 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::hc276eb29c2a0ea9c
  23:        0x10474fb58 - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::h768e976a33efe7ed
  24:        0x1047517cc - winit::platform_impl::platform::app_state::AppState::cleared::hc8bfbb698ade83e3
  25:        0x104753b3c - winit::platform_impl::platform::observer::control_flow_end_handler::h8943515001931390
  26:        0x18069dcc8 - <unknown>
  27:        0x18069db14 - <unknown>
  28:        0x18069d17c - <unknown>
  29:        0x18069c5e8 - <unknown>
  30:        0x1885b72a0 - <unknown>
  31:        0x1885b7014 - <unknown>
  32:        0x1885b6dd4 - <unknown>
  33:        0x182e8b480 - <unknown>
  34:        0x182e89e20 - <unknown>
  35:        0x182e7bcac - <unknown>
  36:        0x1046162a4 - winit::platform_impl::platform::event_loop::EventLoop<T>::run::h7a09a9112611bdb8
  37:        0x10464aca0 - winit::event_loop::EventLoop<T>::run::h7d2cfc3630d5dfc4
  38:        0x10464c590 - binocle::event_loop::run::h2215f87075e3354e
  39:        0x10464e498 - binocle::main::h40910ed9e9268e67
  40:        0x104620bd0 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha08954ce2f1ff040
  41:        0x10462358c - std::rt::lang_start::{{closure}}::h63f9deb1c3f1f84d
  42:        0x10487eeb0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he38288968a08ce30
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  43:        0x10487eeb0 - std::panicking::try::do_call::hc5ee1d2a64b67a7c
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  44:        0x10487eeb0 - std::panicking::try::h6456708f12a6b661
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  45:        0x10487eeb0 - std::panic::catch_unwind::h0912a030777d678b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  46:        0x10487eeb0 - std::rt::lang_start_internal::{{closure}}::hd9cb206594099c49
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  47:        0x10487eeb0 - std::panicking::try::do_call::h75969ed557adb08d
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  48:        0x10487eeb0 - std::panicking::try::hd457662d949840e3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  49:        0x10487eeb0 - std::panic::catch_unwind::he3438363c58e9600
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  50:        0x10487eeb0 - std::rt::lang_start_internal::h103433e957e14c30
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  51:        0x10464e5a8 - _main
-[_MTLCommandEncoder dealloc]:131: failed assertion `Command encoder released without endEncoding'
zsh: abort      env RUST_BACKTRACE=full binocle PM_PRISM.gbc
```

**Comment by sharkdp** [comment]
> Hmm ok, as far as I'm concerned it's not working on Debian Linux x86_64 , though :/ I haven't found a system it's working on tbh. :(

Oh :-/. It's working on Ubuntu 20.04 for me as well.

Could someone please try to run this minimal example here: https://github.com/parasyte/pixels/tree/master/examples/egui-winit? This is what binocle is based on.

**Comment by sharkdp** [comment]
I updated the dependencies for binocle. Could someone please build from master and try again? If that doesn't work, I can also provide binaries.

**Comment by simonsan** [comment]
> I updated the dependencies for binocle. Could someone please build from master and try again? If that doesn't work, I can also provide binaries.

Compiled from `master`, same error.

**Comment by sharkdp** [comment]
I also found another weird thing which I just fixed on master. It might be worth to update to the latest commit and try again.

**Comment by sharkdp** [comment]
I released a new version if someone else wants to give this a try: https://github.com/sharkdp/binocle/releases/tag/v0.1.2

**Comment by simonsan** [comment]
> I released a new version if someone else wants to give this a try: https://github.com/sharkdp/binocle/releases/tag/v0.1.2

Tried it with an uploaded binary from the releases on Windows (x68_64) and now it works.

**Comment by sharkdp** [comment]
> Tried it with an uploaded binary from the releases on Windows (x68_64) and now it works.

awesome. thank you!

Could someone on MacOS verify if this fixes the problem as well?

> Could you publish on `crates.io` please, as well?

Done

**Comment by simonsan** [comment]
@sharkdp Thank you :)
