### ISSUE TITLE
wayland error

### ISSUE THREAD

**Issue by AlienJust** [sharkdp/binocle#47]
Hi, Im trying to run binocle under sway wm and got this:

binocle some_file.bin
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    45824 IOT instruction (core dumped)  binocle some_file.bin
```

WAYLAND_DEBUG=1 binocle some_file.bin     
```[2208543.715]  -> wl_display@1.get_registry(new id wl_registry@2)
[2208543.755]  -> wl_display@1.sync(new id wl_callback@3)
[2208547.677] wl_display@1.delete_id(3)
[2208547.713] wl_registry@2.global(1, "wl_shm", 1)
[2208547.798]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@4)
[2208547.836] wl_registry@2.global(2, "wl_drm", 2)
[2208547.850] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 4)
[2208547.860] wl_registry@2.global(4, "wl_compositor", 5)
[2208547.871]  -> wl_registry@2.bind(4, "wl_compositor", 5, new id [unknown]@5)
[2208547.884] wl_registry@2.global(5, "wl_subcompositor", 1)
[2208547.901]  -> wl_registry@2.bind(5, "wl_subcompositor", 1, new id [unknown]@6)
[2208547.914] wl_registry@2.global(6, "wl_data_device_manager", 3)
[2208547.924] wl_registry@2.global(7, "zwlr_gamma_control_manager_v1", 1)
[2208547.934] wl_registry@2.global(8, "zxdg_output_manager_v1", 3)
[2208547.943] wl_registry@2.global(9, "org_kde_kwin_idle", 1)
[2208547.952] wl_registry@2.global(10, "ext_idle_notifier_v1", 1)
[2208547.961] wl_registry@2.global(11, "zwp_idle_inhibit_manager_v1", 1)
[2208547.971] wl_registry@2.global(12, "zwlr_layer_shell_v1", 4)
[2208547.982] wl_registry@2.global(13, "xdg_wm_base", 2)
[2208547.997] wl_registry@2.global(14, "zwp_tablet_manager_v2", 1)
[2208548.017] wl_registry@2.global(15, "org_kde_kwin_server_decoration_manager", 1)
[2208548.047] wl_registry@2.global(16, "zxdg_decoration_manager_v1", 1)
[2208548.084]  -> wl_registry@2.bind(16, "zxdg_decoration_manager_v1", 1, new id [unknown]@7)
[2208548.109] wl_registry@2.global(17, "zwp_relative_pointer_manager_v1", 1)
[2208548.131]  -> wl_registry@2.bind(17, "zwp_relative_pointer_manager_v1", 1, new id [unknown]@8)
[2208548.160] wl_registry@2.global(18, "zwp_pointer_constraints_v1", 1)
[2208548.195]  -> wl_registry@2.bind(18, "zwp_pointer_constraints_v1", 1, new id [unknown]@9)
[2208548.219] wl_registry@2.global(19, "wp_presentation", 1)
[2208548.238] wl_registry@2.global(20, "zwlr_output_manager_v1", 4)
[2208548.278] wl_registry@2.global(21, "zwlr_output_power_manager_v1", 1)
[2208548.298] wl_registry@2.global(22, "zwp_input_method_manager_v2", 1)
[2208548.317] wl_registry@2.global(23, "zwp_text_input_manager_v3", 1)
[2208548.339]  -> wl_registry@2.bind(23, "zwp_text_input_manager_v3", 1, new id [unknown]@10)
[2208548.360] wl_registry@2.global(24, "zwlr_foreign_toplevel_manager_v1", 3)
[2208548.377] wl_registry@2.global(25, "ext_session_lock_manager_v1", 1)
[2208548.393] wl_registry@2.global(26, "wp_drm_lease_device_v1", 1)
[2208548.408] wl_registry@2.global(27, "zwlr_export_dmabuf_manager_v1", 1)
[2208548.424] wl_registry@2.global(28, "zwlr_screencopy_manager_v1", 3)
[2208548.440] wl_registry@2.global(29, "zwlr_data_control_manager_v1", 2)
[2208548.456] wl_registry@2.global(30, "zwp_primary_selection_device_manager_v1", 1)
[2208548.472] wl_registry@2.global(31, "wp_viewporter", 1)
[2208548.489] wl_registry@2.global(32, "wp_single_pixel_buffer_manager_v1", 1)
[2208548.505] wl_registry@2.global(33, "zxdg_exporter_v1", 1)
[2208548.522] wl_registry@2.global(34, "zxdg_importer_v1", 1)
[2208548.534] wl_registry@2.global(35, "zxdg_exporter_v2", 1)
[2208548.544] wl_registry@2.global(36, "zxdg_importer_v2", 1)
[2208548.553] wl_registry@2.global(37, "xdg_activation_v1", 1)
[2208548.567] wl_registry@2.global(38, "zwp_virtual_keyboard_manager_v1", 1)
[2208548.582] wl_registry@2.global(39, "zwlr_virtual_pointer_manager_v1", 2)
[2208548.597] wl_registry@2.global(40, "zwlr_input_inhibit_manager_v1", 1)
[2208548.613] wl_registry@2.global(41, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[2208548.628] wl_registry@2.global(42, "wl_seat", 8)
[2208548.657]  -> wl_registry@2.bind(42, "wl_seat", 6, new id [unknown]@11)
[2208548.685] wl_registry@2.global(43, "zwp_pointer_gestures_v1", 3)
[2208548.703] wl_registry@2.global(44, "wl_output", 4)
[2208548.727]  -> wl_registry@2.bind(44, "wl_output", 3, new id [unknown]@12)
[2208548.758] wl_callback@3.done(6150)
[2208548.784]  -> wl_display@1.sync(new id wl_callback@3)
[2208549.574] wl_display@1.delete_id(3)
[2208549.596] wl_shm@4.format(0)
[2208549.611] wl_shm@4.format(1)
[2208549.619] wl_shm@4.format(875709016)
[2208549.628] wl_shm@4.format(875708993)
[2208549.639] wl_shm@4.format(875710274)
[2208549.651] wl_shm@4.format(842094674)
[2208549.660] wl_shm@4.format(842088786)
[2208549.668] wl_shm@4.format(892426322)
[2208549.678] wl_shm@4.format(892420434)
[2208549.686] wl_shm@4.format(909199186)
[2208549.694] wl_shm@4.format(808665688)
[2208549.701] wl_shm@4.format(808665665)
[2208549.710] wl_shm@4.format(1211384408)
[2208549.723] wl_shm@4.format(1211384385)
[2208549.737] wl_shm@4.format(942948952)
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    46110 IOT instruction (core dumped)  WAYLAND_DEBUG=1 binocle some_file.bin
```

sudo RUST_BACKTRACE=full binocle some_file.bin
```
Authorization required, but no authorization protocol specified

thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:612:9
stack backtrace:
   0:     0x558edaa3634c - <unknown>
   1:     0x558edaa597ec - <unknown>
   2:     0x558edaa32655 - <unknown>
   3:     0x558edaa37f20 - <unknown>
   4:     0x558edaa37ad5 - <unknown>
   5:     0x558edaa385d4 - <unknown>
   6:     0x558edaa380b0 - <unknown>
   7:     0x558edaa367f4 - <unknown>
   8:     0x558edaa38019 - <unknown>
   9:     0x558eda4b4a91 - <unknown>
  10:     0x558eda6b4124 - <unknown>
  11:     0x558eda545c53 - <unknown>
  12:     0x558eda4f09e9 - <unknown>
  13:     0x558eda4dfed3 - <unknown>
  14:     0x558eda52ad6d - <unknown>
  15:     0x558edaa35fdb - <unknown>
  16:     0x558eda4f0a12 - <unknown>
  17:     0x7f1189767290 - <unknown>
  18:     0x7f118976734a - __libc_start_main
  19:     0x558eda4b523e - <unknown>
  20:                0x0 - <unknown>
```

**Comment by sharkdp** [comment]
Thank you for reporting this. I'm not going to work on this myself, but maybe someone else can help out.

**Comment by mischw** [comment]
I also use sway wm and get a similar error

binocle tools.zip
```
[2023-06-09T11:08:12Z ERROR binocle::event_loop] pixels.render() failed: The GPU failed to acquire a surface frame.
```

sudo RUST_BACKTRACE=full binocle tools.zip
```
Authorization required, but no authorization protocol specified

thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9
stack backtrace:
   0:     0x55d811d4db1a - <unknown>
   1:     0x55d811d7019e - <unknown>
   2:     0x55d811d4ad75 - <unknown>
   3:     0x55d811d4d8e5 - <unknown>
   4:     0x55d811d4f0cf - <unknown>
   5:     0x55d811d4ee0b - <unknown>
   6:     0x55d811d4f7d9 - <unknown>
   7:     0x55d811d4f579 - <unknown>
   8:     0x55d811d4dfcc - <unknown>
   9:     0x55d811d4f282 - <unknown>
  10:     0x55d811814213 - <unknown>
  11:     0x55d811a1645a - <unknown>
  12:     0x55d8119f01ca - <unknown>
  13:     0x55d811845862 - <unknown>
  14:     0x55d8118b7d01 - <unknown>
  15:     0x55d81189eb53 - <unknown>
  16:     0x55d81182d07d - <unknown>
  17:     0x55d811d45e1c - <unknown>
  18:     0x55d8118b7e7c - <unknown>
  19:     0x7fa5337f6850 - <unknown>
  20:     0x7fa5337f690a - __libc_start_main
  21:     0x55d811814855 - <unknown>
  22:                0x0 - <unknown>
```

Any idea why this is happening?
